"""Initial Migration - create Beer and Venue tables

Revision ID: 97eb43767c8a
Revises: 
Create Date: 2021-06-29 09:20:04.893936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97eb43767c8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abv', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('style', sa.String(length=80), nullable=False),
    sa.Column('bid', sa.String(length=25), nullable=False),
    sa.Column('brewery_name', sa.String(length=80), nullable=False),
    sa.Column('brewery_slug', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('major_style', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('venue_blob', sa.String(length=180), nullable=True),
    sa.Column('beer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beer_id'], ['beer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue')
    op.drop_table('beer')
    # ### end Alembic commands ###
