import os

SECRET_KEY = os.urandom(32)
# Grabs the folder where the script runs.
basedir = os.path.abspath(os.path.dirname(__file__))

# Enable debug mode.
DEBUG = True

# Connect to the database
# COMPLETED IMPLEMENT DATABASE URL and set other options for SQLAlchemy
SQLALCHEMY_DATABASE_URI = 'postgresql://postgres@localhost:5432/nearbeer'
# Prevent warning concerning use of Flask-SQLAlchemy event system causing overhead in memory usage
SQLALCHEMY_TRACK_MODIFICATIONS = False

# For unit testing purposes 
TEST_BREWER_AUTH_TOKEN = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldIdHhPZnhSeUZTYWw1TTJjN2lPeSJ9.eyJpc3MiOiJodHRwczovL3Byb2R1Y3QtZGVtb3MudXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwZTg4NWJlNTMwODA5MDA2OGZmZjU0MiIsImF1ZCI6WyJiZWVybmVhciIsImh0dHBzOi8vcHJvZHVjdC1kZW1vcy51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjI3NDIyOTE5LCJleHAiOjE2Mjc0MzAxMTksImF6cCI6InppUjNDdXczU1dtRmhrUFdmVGhGOUxEejdna1huTUg2Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbImRlbGV0ZTpiZWVycyIsImdldDpiZWVyLWRldGFpbHMiLCJnZXQ6YmVlcnMiLCJnZXQ6c3R5bGVzIiwicGF0Y2g6YmVlci11c2VyLXJhdGluZyIsInBvc3Q6YmVlcnMiLCJ2aWV3OnNpbXBsZSJdfQ.AXUgNW9DBayzYzGqrQHcgJkaNraIY8tT-OfCuXgooipeEdomxcxAwxe8foDD-iATRA_rgoM7vdqpjhdrE9O5UTaxO-uqSTJCslNIzI4ShTJiVeKN8Hma5Wlk97HCGiSiJ3NSd-sV-WxiSjBxr4l197Z7Ydn0jEEOa1fbckrt4KiFp39CUIEPXDB6gPyVpasznggq6SsB0fM3-9mPSjMKI-QC9NClBdgfSCu0R18FQOFxwBx2H9I6jkhAFTT-YJ1XnNqdZJU44-HPGMG5VabT-kfErz7gWj_YY4kPvbriq4bVZFT-7KaCW4AEa9k9NTQR6wcBoIsuLCITVjC9VfodMw'
TEST_BEER_LOVER_AUTH_TOKEN = ''
TEST_INVALID_TOKEN = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldIdHhPZnhSeUZTYWw1TTJjN2lPeSJ9.eyJpc3MiOiJodHRwczovL3Byb2R1Y3QtZGVtb3MudXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwZTg4NWJlNTMwODA5MDA2OGZmZjU0MiIsImF1ZCI6WyJiZWVybmVhciIsImh0dHBzOi8vcHJvZHVjdC1kZW1vcy51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjI2MzYwNTM5LCJleHAiOjE2MjYzNjc3MzksImF6cCI6InppUjNDdXczU1dtRmhrUFdmVGhGOUxEejdna1huTUg2Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbImRlbGV0ZTpiZWVycyIsImdldDpiZWVyLWRldGFpbHMiLCJnZXQ6YmVlcnMiLCJnZXQ6c3R5bGVzIiwicGF0Y2g6YmVlci11c2VyLXJhdGluZyIsInBvc3Q6YmVlcnMiLCJ2aWV3OnNpbXBsZSJdfQ.qt7Xv8TyJKoqqx-izkMnylx_KVTn9XLVCsET5RmmVQyJs_4yg_wiwpqqwh5W7nxkBUd6tHzMCd3vfrBwOm3Xfdn7iGYqTsBjpSsusuCo0vWlsiCiX73EZi6X6t70lmvEvyZ2L81NVUfBpMc1Yhmo_w9i9srpgys-wZj-QY5Fo77Vsx4Nih5zGR8bTgbWIWBmI1odYmoATTJfNNP3iwlbbigpnAbViU316PI5MFHCaSBWp3Q9NL_Tb6Qd1j41ezj3kPqF0TlGuPo-Lpz1BOxcbDboFnzei8g4nhfFzU1gSNeCUZdeEJViON_2VaVkV0HLaYeRL8xeaP54PUnbzNEySP'
