"""associtation table for beer and venues BeerVenues class

Revision ID: 7b4aa604cd44
Revises: e8a5890deb33
Create Date: 2021-07-06 02:21:53.915083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4aa604cd44'
down_revision = 'e8a5890deb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beervenue',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('beer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beer_id'], ['beer.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'beer_id')
    )
    op.drop_constraint('venue_beer_id_fkey', 'venue', type_='foreignkey')
    op.drop_column('venue', 'beer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('beer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('venue_beer_id_fkey', 'venue', 'beer', ['beer_id'], ['id'])
    op.drop_table('beervenue')
    # ### end Alembic commands ###
